services:
  api: &api
    build:
      context: ./SuppHubBackend/supphub
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./SuppHubBackend/supphub:/app
    restart: always
  database:
    image: postgres:17.5
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
        API_NOVA_POST: ${API_NOVA_POST}
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - api
    restart: always

volumes:
  pgdata:
