# Generated by Django 5.2.4 on 2025-08-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("price", models.PositiveIntegerField()),
                ("hit", models.BooleanField(default=False)),
                ("vegan", models.BooleanField(default=False)),
                ("img", models.TimeField()),
            ],
            options={
                "db_table": "products",
            },
        ),
    ]
