# Generated by Django 5.2.4 on 2025-08-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.TextField(blank=True, null=True),
        ),
    ]
