# Generated by Django 5.2.4 on 2025-08-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="hit",
            new_name="hitBool",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="vegan",
            new_name="veganBool",
        ),
    ]
