# Generated by Django 5.2.8 on 2026-01-07 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_hit_product_hitbool_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                (
                    "discount",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "promocodes",
            },
        ),
    ]
