# Generated by Django 5.2.8 on 2026-01-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_promocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
