# Generated by Django 5.2.8 on 2026-01-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_promocode_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocode",
            name="is_active",
        ),
        migrations.AddField(
            model_name="promocode",
            name="useges_amount",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
