# Generated by Django 5.2.8 on 2026-01-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_promocode_is_active_promocode_useges_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promocode",
            old_name="useges_amount",
            new_name="usages_amount",
        ),
    ]
