# Generated by Django 5.2.8 on 2026-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_rename_useges_amount_promocode_usages_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="amount",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
