# Generated by Django 5.2.8 on 2026-01-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
