# Generated by Django 5.2.8 on 2026-01-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active_ingredients",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="certificate",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="pill_amount",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="pill_form",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="producer_country",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
