# Generated by Django 5.2.10 on 2026-01-21 12:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_active_ingredients_product_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
