# Generated by Django 5.2.10 on 2026-01-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255, null=True, verbose_name="URL"),
        ),
    ]
