# Generated by Django 5.2.10 on 2026-01-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name="URL"),
        ),
    ]
