# Generated by Django 5.2.10 on 2026-02-07 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(
                max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)]
            ),
        ),
    ]
