# Generated by Django 5.2.10 on 2026-02-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_promocode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
