# Generated by Django 5.2.7 on 2025-11-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sendsms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
