# Generated by Django 5.2.7 on 2025-11-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sendsms", "0002_alter_smsmessage_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smsmessage",
            name="message",
        ),
    ]
