# Generated by Django 5.2.7 on 2025-11-12 21:04

import sendsms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sendsms", "0003_remove_smsmessage_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="status",
            field=models.CharField(
                choices=sendsms.models.SMSStatus.choices, default=sendsms.models.SMSStatus["PENDING"], max_length=20
            ),
        ),
    ]
